/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecificationRouteImport } from './routes/specification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LifestyleRouteImport } from './routes/lifestyle'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as PropertiesSlugIndexRouteImport } from './routes/properties.$slug.index'
import { Route as PropertiesSlugApartmentsAptSlugRouteImport } from './routes/properties.$slug.apartments.$aptSlug'

const SpecificationRoute = SpecificationRouteImport.update({
  id: '/specification',
  path: '/specification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleRoute = LifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesSlugIndexRoute = PropertiesSlugIndexRouteImport.update({
  id: '/properties/$slug/',
  path: '/properties/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugApartmentsAptSlugRoute =
  PropertiesSlugApartmentsAptSlugRouteImport.update({
    id: '/properties/$slug/apartments/$aptSlug',
    path: '/properties/$slug/apartments/$aptSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/lifestyle': typeof LifestyleRoute
  '/login': typeof LoginRoute
  '/specification': typeof SpecificationRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/$slug/': typeof PropertiesSlugIndexRoute
  '/properties/$slug/apartments/$aptSlug': typeof PropertiesSlugApartmentsAptSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/lifestyle': typeof LifestyleRoute
  '/login': typeof LoginRoute
  '/specification': typeof SpecificationRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin': typeof AdminIndexRoute
  '/properties/$slug': typeof PropertiesSlugIndexRoute
  '/properties/$slug/apartments/$aptSlug': typeof PropertiesSlugApartmentsAptSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/lifestyle': typeof LifestyleRoute
  '/login': typeof LoginRoute
  '/specification': typeof SpecificationRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/$slug/': typeof PropertiesSlugIndexRoute
  '/properties/$slug/apartments/$aptSlug': typeof PropertiesSlugApartmentsAptSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/faqs'
    | '/lifestyle'
    | '/login'
    | '/specification'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/'
    | '/properties/$slug/'
    | '/properties/$slug/apartments/$aptSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faqs'
    | '/lifestyle'
    | '/login'
    | '/specification'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin'
    | '/properties/$slug'
    | '/properties/$slug/apartments/$aptSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/faqs'
    | '/lifestyle'
    | '/login'
    | '/specification'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/'
    | '/properties/$slug/'
    | '/properties/$slug/apartments/$aptSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  LifestyleRoute: typeof LifestyleRoute
  LoginRoute: typeof LoginRoute
  SpecificationRoute: typeof SpecificationRoute
  PropertiesSlugIndexRoute: typeof PropertiesSlugIndexRoute
  PropertiesSlugApartmentsAptSlugRoute: typeof PropertiesSlugApartmentsAptSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specification': {
      id: '/specification'
      path: '/specification'
      fullPath: '/specification'
      preLoaderRoute: typeof SpecificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle': {
      id: '/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof LifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$slug/': {
      id: '/properties/$slug/'
      path: '/properties/$slug'
      fullPath: '/properties/$slug/'
      preLoaderRoute: typeof PropertiesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug/apartments/$aptSlug': {
      id: '/properties/$slug/apartments/$aptSlug'
      path: '/properties/$slug/apartments/$aptSlug'
      fullPath: '/properties/$slug/apartments/$aptSlug'
      preLoaderRoute: typeof PropertiesSlugApartmentsAptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  LifestyleRoute: LifestyleRoute,
  LoginRoute: LoginRoute,
  SpecificationRoute: SpecificationRoute,
  PropertiesSlugIndexRoute: PropertiesSlugIndexRoute,
  PropertiesSlugApartmentsAptSlugRoute: PropertiesSlugApartmentsAptSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
